export type {
  Capability,
  CapabilityInput,
  CapabilityMatch,
  CapabilityMetadata,
  CapabilityOutput,
  DiscoveryResult,
  InspectionResult,
  InspectionStatus,
  JsonSchemaType,
  JsonSchemaValue,
  Provider,
  ProviderMetadata,
  PublishInput,
  PublishResult,
  PublishStatus,
  VerificationStatus,
  WebMCPSchema,
} from "@/lib/types/axiom";
